### ISSUE TITLE
Begin research and layout of iOS MainScreen

### ISSUE THREAD

**Issue by lucaswalter** [lucaswalter/Beta-Chi-Daily-Update#11]
Check out Xamarin's getting started with iOS: https://developer.xamarin.com/guides/ios/getting_started/hello,_iOS/hello,iOS_quickstart/

Then play around with TextViews, Labels, Buttons, and ActionBars to try and setup a similar looking view to the android app.

It will need all of the same buttons and information to display so I would start there.

**Comment by cameronsmith223** [comment]
data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxQTEhUSERIUFBAUFBgVFBYUFRQUGBAVFBYWFxUVFRQYHCggGBolGxQUITEhJSkrLi4uFx8zODMsNygtLisBCgoKDg0OGhAQGiwcHBwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCssLCw3LCs3NywrLCssK//AABEIAOEA4QMBIgACEQEDEQH/xAAcAAEAAQUBAQAAAAAAAAAAAAAABwECBAUGAwj/xABIEAABAwIDBQUDCAYHCQEAAAABAAIDBBESITEFBgdBURNhcYGRIjLwFCNCUqGxwdEkNHJ0grMWQ2JzouHxMzZUY3WSk6OyFf/EABkBAQADAQEAAAAAAAAAAAAAAAABAgMEBf/EAB0RAQADAAIDAQAAAAAAAAAAAAABAhEhMQMSQQT/2gAMAwEAAhEDEQA/AJeSyJdTrsVe6w1GnNQ5xN4gE/o9K8saMQkkabF/LC22eHvXUcV9vGnphGx1nzYhivm1jSMVhzvp6r5+qX4jfxNzqe8qJ7Ijh7x1775E3J1ubmyzYdoFgxcyeuht8eq1cLSMuqunYSB0yHhkkzCYiYdxu7xBfTtIsSCMhc+yet1mM4lzm3tYW91tSfpE3uo1aTp8BZdK/kTkR3ddVELQmDd3iXeUR1PsxWPzjm+6eVyL5XUk0ldHK3FFIyRut2ODh9i+YwLi2VwDblfu71n7rbefRzCVmZGJrm5gOB1B6puD6YCLA2JtVlTCyaM+y8XtzaeYPeCs66vXJUVREVJjAREUAiIgIiICIiAiIgIiICIiAiIgLC2rtBkEbpHnJvqTfIDvKzC5RFxE292suBpJiiJabaF1/ad5aeSmyYjXG787bfVS45L4W4mtA0a240C52MXGff0XpVuB63z55cslkbKp754euqpNm1Kq0lAXZWsOd/BZjdktuBc6fgtrGy1grhH9/wCCymzp9eHJ12zsBFswdO7qsGKMaDP/AFXY7SpcTe8aePRciBgytn/nkt6Tw5b1yW0o4MTbXs4e6c9ehuvCsiNr5Ai+IfiFZT1ZyF9OXTNe9QRbIHFnrzHcQjLnXccIN4eymMD3fNTHK+jZOVul8x6KbV8vbEns4fRdfLlmLar6S2FXdtAyT6WGzv2m5O+0faphazZDRFUKgV7KCIizBERAREQEREBERAREQEREBERBHG/m8MmIQQOt9cjU87XUVbSndezT7BzPmbm58V09ZP7Nx7TzqSfade97eq0U1GZHDC2zCT9hsqe2Oz1j41dBSGR1rXGZz7iF0cFNh8rr3pqVsYsO/PJezHDxWczq0cKNg6i6vhp9LDnoshjOayKdlrLKXRHTxdRZaeq5nbew8sTW2Nulgc9V3QzVsrARYi63i2KWpEwiU0zo88PmfFekVTkbt6+Hku12lslrge/81oarY2AeyCb3vnny5K1Z1yeTxtdC0HCRkL9ym/hZWF0MkbtWPB8Q8Gx/wqHKHZoNrk2yP7IN73BUvcLIrCcgeyOzjHeWNJd/9hXiOVLdO/VFXkqBaW6YiIizSIiICIiAiIgIiICIiAiIgIiIIGdHY2uDewHOw5r1AAAAHwSrQ3Mk6r1pxc3+NVja0vQrC6aC40utfI5rM3gsuS0HW/lrzXTxwjD6/eFgbQ2W2TDiHukkEEi1vBK5HaJrrX0VeAQDnfTO4OWRC3UJB0z/ANFqdr7Mb7JjbgwgNHXIW8+S9NmyOAF9f8lSY2WlbZ22eKyoX5D4zVzZQQvCQ9Emq3s8pj5rymiGFxPRxXs1t1btVvsCMauuCe7LJa0hy+Szk6APqZhFG05kCzeZ5X8yVPe7GyBSwMiGbs3PP1nuzcfu9FxvC7dfA99S8ZZsjy1P0nD7QpKW9XPNlQiIosoIiKoIiICIiAiIgIiICIiAiIgIiIIHvp5K+Bnx5rHvoOq2NJGMr9PxWOa9KnDKhe4d4V09VYeqs7UDU9VqWVeO+eedh0TE78ZTn4iLlZTyAA1ubjp42WNFHaxPP8llQMs4fHJUhW1Wk2jWPhw422a42BB1tf8AJZtJWhzRiNjkvbadE2bBiJBbfToQQRZYrqA9qGMYRGWNLSdQRYELbhjOw3dPZrS/kASfLktjsPdaWZ4lm9iMknPW3IAcvFZW6mx+0c0nOKM3df6bx9HwCkDCtYqwtb48qeIMaGNFmtFgOgCvcrkKmOIZgREVZnQREUAiIgIiICIiAiIgIiICIiAiIggWEXcOlgsiqcQAW55aeawKaTEAs4NNvjqsNnXpV5gpKgPGfvcwfFeNbQ5tc02eL+eWiv8AkgdYtOGQXsvVtVnZ7bON8+XiFaUT2upq0ktY8ZjTpey2EUZFifjJYoAFjqvd0+g5qsRspteIh7OYCRfLRZdFTl72NaPbdk3uF7Fx7grNm7LklIwtLtL9B4ld5sLY4hFznIRmeg6DuW9auS9mdQ0gjY1jdALePUrKKAItJ34wERVVfWRRERIqCKqokxgIiKMBERT6giqAqJgIiKARVVFPrIIgRPUESyJ6j5s2VPydqujpHggD41Wkq9mkkOZkfvVtDXkey/I87881jmuytpq6CWHPLvVojxA4hpdUp6gOOXRZ0NOXENbm91wGjMnySKlvI10ULgbA3HTyXQ7v7IdO8Ae6LXdyAt962mxtyn3Dpjhb9UG7j4nku3pKRkbcLGhrR0Wta4xvfVlBRNiYGMFgPUnqeqywFa54AJJAAFyTyA1KhXe/ivPJIYdnezGDhEgbifKb2uwch0yuVtEMe02EK0KACdvhvak1mG1+WnXBr9i3m5XFaTtWwbQsWudhEtsLo3XsBI3pfnyUCZQUWq3mqHR0dTJG6z2U8r2OHJzY3FpHmAoG2ZvhteoeWQVE0jwMRaxrCQ0WBNraXI9VMRo+jlaoEftXeBvtO+VWGZ+bacueQC3fD3idNJUMpq3C4SODGSgBpa85Na8DIgnK/UhRn0TEllRVCpnKAqi+fd5t/K+GuqGMqXdnFVStawhuHCyQgNOWlhZTduzttlZTx1Eej25j6jx7zD3g3C0mMG0uhURcYd56ulqomU07o2Opw8hts3Y5BfMdGhSfsSZz6eB7jd7oY3OPUuYCT6qs9pZwRaDfnbfyOhmmBtIG4Yv7x/ss9Cb+RUKbA4kVrKmJ1RUvkp+0HaNdht2ZNnHIcgb+SnOB9FIVax9xcZg5gjmCuJ4vbYmpaOOSnkMbzUNYSLZtMcpIz72j0URA7gIuE4PbYnqqSWSpkMj21BYC62TRHEQMu9x9V029lU6KiqZYzhkZTyOYR9FzWOIPqFNY2SW1CKIeD+9NXV1cjKmd0jBTl4DrZOEkYvkOjj6qX7KLCioqoq5IhKKQGyw56Rjjcj4uuu/oeRn2jQMtAVWPd2MH2nOf3e6NfVdEfniO1p/RvTj4aU3sy/PTy9FIPDSCB0TpWHFKHuY8n6FtA3oCLFcNvzt6OBvySmAEjwe2cNWMJBw3+sR9i1nDvewUdR84T2Evsyf2D9F/lp4FZ38cR0rW+9voNquXlE8EAggg5gjQg6EL1VJjhMuR4rV5h2bMWmzpCyK45CRwDrfw4lwHAnYjJJZqp7QTDhZFfPC59y53iAAB4ldvxipS/ZkhaL9nJE8/sh4aT/iXJ8AtoNHymnJAccErf7QALXW8PZ9VeekQmMDJQNxy2MyGpimjGH5Qx5eBkC+MtBdbqQ8einkFQhx7rmunpoQbuijkc4dO1czCD5R381WI41V2WyNomfd90jzd/wAinY4nmYmSR3PjhB81GPCDbENLWvkqJGxsNO5gc7TEXRkD0aVIu7dIY93XB2RdR1MnlIJXN+whRXw53ZZtCqdBI9zGiF0l2WvdrmNAz5e2VbchP1N83EfZzRf5Uw9zQ4k+AsoR2REazarTA0tElX2oAH+zjEvaFxtpYfasriBuJJs4se15kp3mweRYsdrhfbryPcVI/B2topIXCngbDVNAEwuXOeOT2udnhJ5ciqzKYSQ5UBREiEPmTb+z3VG1qmBlg+StnY2+mIvdZdBwk3mNHVOpJ7timfgIdl2M4yF+l/dPfZYdN/vCf+pSfzXLdcat1eylbXQizJXWmt9CSwwv7sVvUd6tuydMbjyf02H91b/MmUy7ufqlP+7w/wAtq+bN7N4nVop3yf7WKnEMh+uWvkIf4lrhfvuvo/YUwZRQOcbNbTROcegETSSkxspRXx325ikho2nKNvbSftOyYPJuI/xBaHfbc40lBRT4bPcwtqO58l5GX8AXN8gud2ntvt611XK3G10weWE2vG1wwx35eyAF1+9fFJtbSyUz6QNDwLO7S+BzXAtcBbqFPCEj8J9t/KaBgcbyQfMv/h9w+bMPmCtZx2/UIv3pv8qZcPwV232NYYHH5upbhHdIy7mHzGMeYXccd/1CL96b/KmVY7TLluFe/FLQ00kVQ54e+cvAawuGExxt1He0rod5uJ1BNSVEMbpO0khkY28bgMTmEC55Zlc1wt3Gpq+mklqO0xtnMYwPwjCGRu0trdxXQ7ycLqKCknnZ22OKGR7byXGJjCRcWzFwpr2mYc1wF/X5f3R382FTyVA3Ab9fl/dHfzYVPBVZ7RKiIi09oHGQVOOON31mNd/3C/4rnt6t4BTxOcD7ViB4nQD71nQSFsUbTk4Ma092EYfwUS77bZ7eYNYfmo7gf2nXN3LovZzUhz8tQ5zi9xu5xJJ7ybqjnrzDkJ/FZTymOEycIN98hQ1LtMoHk/8ArJ+70Uvr5Bp5yxwc0kEG4I5EaL6I4b75CtjEch/SY2jF/wA1oyxDv6rG3Euis67KrpmyxujkGJj2lrh1DgQfvXz7t7dCt2XUCamxuja68c0YLi0X92QDTLI8ivoe6WURIgR3F2uLMAZCJLWxYHX8cN7XXhuruRVbSn7erEjYXPL5ZJLtdLpdrAc89L6AKfPkUd79my/XC2/rZe4ClOtLvTAG7PqWMFmikma0DoInAABRDwNhc3aD7tcB8leLkEZ44ss/BTwqBgGgChDB29siOqgfTzC7JBbvadWub3g2PkvnekbU7J2hfA4vhdY2DsM8TtdNQW5joQOi+l1bgHMD0UDxoK1s0TJYzdkjQ5vI2PUciskKluirdTqHz5SwO/pAThdh/wD0nm9ja3aOzup42ts5lRC+CUXjkaWuHiNR3g2PksnAOg9Fcn1L5U3i3elpaiSnexxLDk4NJD2kXa4EDmD96l/f3arodjQRMDu0qIYYrAG7WYGmQ2Gegw/xKSiwcwEc0HkkiHeC+6jJI5qiphDwXCKNsjLizfae4A95A8ipM/otR/8ACQf+Nn5LbgAaIoHzpxB2K+h2kX07C1mMVEJa02abg2y6Pa7LpZdzxXrflOyaWZjXfOTRvLbElpMMtwR3HJSi5gOoCpgHQJvIjjgVGW0UwcCD8pccwR/VRdV12+rSdn1YAJPyaUADO943clumttoqlTEiDOBMDm1spc1w/RiMwR/WxdfBTmqBo6KqT0KqiIq6IU4kbe7FojZlJKNebWk5nz081ExPx5rK2rtJ9RI6WQkucb+A5Ad1rLBJW97Y58yOFWlXfkV5gqpd+KrHkhHOLiM1u92dsvpp45YzZzHA/tC2bT3EZLRBy9oXWVJ5lr45x9Y7D2oyphZNGfZcAf2TzafArYhQHww3xNNKIpXfo8hDTz7NxyDx+Knljr5jRV+te3ohRCrTKqiIiz1IiIgIiJoIiJoIiJoIiICIiaCIiaCIiaCIiaPjkKxVui6LcudQKlvxVSECziopZXtOapZLK/qlkxykEWU4cKd92SRspJ32lFmxE/TGuEn6wzA7lBDTmtru85wqIOz9/to8NuuMAfes7tfG+sb5IqKqrKwiIqgiIgIiICIiAiIgIiICIiAiIgIiICIiD44AVEBVb/HmunYYKKoCL1aOXirRVGxqyytsr3FUASVu+lWt/BSJwc2AZqtszh83B7f8ejB6m/kuM2Ls588rI2NLnOIAAzuvpbdHYDKOBsTfeIBkd9Z35DQLG07LesY3tskV1laotCBERZgiIgIiICIiAiIgIiICIiAiIgIiICIiD42uqgaIAvWNl/jvXVWrnlRjF6u9MjZeuD0sb+qxZHXPdmtFVgzXvFHfT4yXmwKQuF+6PyuYPkB7CIhzuWI8mefPuWN5b+Kucu24R7pCGMVUrfnHj5sEe6w/S8T9ykzCrWMAAAFgAAO4BXlZrzJdURFXQREVQREQEREBERAREQEREBERAREQEREBERB8dNYsuNlrH41VKaP8FZUTfRHmu7HOtmmvkNM79+asZ+atWVSQk/b9qrMr0qzNj7MdNI1jG3c5waB45L6W3V2I2kp2QtGYF3n6zj7x/DyXJ8Ldz+wjFTM20rx820/QaR7x7z9gUi2XPOzLbrgsirdUVbIERFUEREBERAREQEREBERAREQEREBERAREQEREHyVD7p8PzWtZqiLuc0qj810G7nvxf3oRFnZv4n1Iz49FeVRFksBERUsCIiqCIiAiIgIiICIiAiIgIiICIiAiIgIiICIiD//Z

**Comment by lucaswalter** [comment]
I don't think you picture worked. lol

**Comment by cameronsmith223** [comment]
I realize. Google "or nah"

**Comment by lucaswalter** [comment]
What was the picture of, I deleted it because it took up crazy amounts of space.

**Comment by lucaswalter** [comment]
We are going to need a Mac to build, deploy, and test this :/

**Comment by cameronsmith223** [comment]
Steal Ernst's

**Comment by cameronsmith223** [comment]
I know with iOS layouts, everything has a definite position relative to the top left corner of the screen. Nothing is relative to other screen elements and everything is given with defined pixel measuerments

**Comment by cameronsmith223** [comment]
I'm not stealing Ernst's laptop.

**Comment by cameronsmith223** [comment]
Can I close this for now? We're at a dead end until we can acquire a Mac.

**Comment by lucaswalter** [comment]
Go for it. You can do the same for all iOS related issues for now if you would like.
