### ISSUE TITLE
Connect everything to Windows Azure Mobile Services.

### ISSUE THREAD

**Issue by lucaswalter** [lucaswalter/Beta-Chi-Daily-Update#13]
We will be able to handle this after we get the Scribe and IM views good to go. After implementing basic CRUB, the next step will to get offline caching working so the apps use unnecessary data.

**Comment by lucaswalter** [comment]
The current step for this is to work with be MainActivity and the reminder adapter. The goal of this adapter is display each of the reminders filtered by date. When the user taps the reminder in ListView they will be prompted  a dialog to add a reminder through the defualt OS provider. When the reminder is held down, they will be given a prompt to delete the reminder.

All of the Database access code for this operation will be located in the MainActivity. Users will only be able to have read access from here.

**Comment by lucaswalter** [comment]
EditScribeDataActivity has been connected to Azure Mobile Services and works properly.

**Comment by cameronsmith223** [comment]
Is the database using SQLite?

**Comment by lucaswalter** [comment]
Currently using an Azure Cloud SQL database, the plan for final release is to implement caching on a SQLite DB to reduce database hits.

**Comment by cameronsmith223** [comment]
Do we know the db structure? Like the tables and rows and columns and
relationships and keys?

**Comment by lucaswalter** [comment]
Yes, the databases are generated off the classes in the "Core" folder. I will get you access to the DB today so you can see what's happening.

**Comment by lucaswalter** [comment]
Next step is to get the set meal functionality working within the EditScribeDataActivity.

**Comment by lucaswalter** [comment]
Implementation of meals is complete, next onto IM.

**Comment by lucaswalter** [comment]
Core Data Model design is complete, everything else is ready to be connected.
