### ISSUE TITLE
Create Icon & Logo for the application.

### ISSUE THREAD

**Issue by lucaswalter** [lucaswalter/Beta-Chi-Daily-Update#16]

**Comment by lucaswalter** [comment]
Maryland added in a nice icon. For the final version we may want to round off the corners and add a slight bevel to get the standard icon look/feel.

**Comment by cameronsmith223** [comment]
I can add a small radius to the corners.........
and skew the view slightly. Want me to?

**Comment by lucaswalter** [comment]
That would be beautiful, we also don't need the file appicon.png, only need to replace that single file.

**Comment by cameronsmith223** [comment]
I realize, sorry.

**Comment by lucaswalter** [comment]
No worries <3
