### ISSUE TITLE
Implement authentication service.

### ISSUE THREAD

**Issue by lucaswalter** [lucaswalter/Beta-Chi-Daily-Update#27]
After doing some research on the Apple App Store, I discovered they unfortunately do not offer a reasonable solution to distribute our app to just a small scale organization. So we will have to release on the public channel then require users to be authenticated. I am going to try and get this set up to work through either a google group or list serve to take away a bit of the manual work of it.

If you guys have any other thoughts or ideas, please let me know. This is feature is still very much in the planning phase.

**Comment by cameronsmith223** [comment]
Is it at all possible to install apps NOT downloaded from the apple
appstore?

**Comment by lucaswalter** [comment]
The only way I know of would be literally jailbreaking everyones device and going through cydi, which seems pretty far from optimal to me. Why can't apple be as neat as Google.

**Comment by lucaswalter** [comment]
Actually, there is ad hoc testing which would have a similar end result, but require each device to have its ID entered before it can even be installed, update would then require USB too.

**Comment by cameronsmith223** [comment]
Cause apple sucks. We can have a question that only our house members know
the answer to. Like who *****\* Janna or something like that.

**Comment by lucaswalter** [comment]
I think you may be right about just a simple pin code for users. We want something that will get in the users way as little as possible. I think we should hold off on this until later as it is no absolutely vital to the operation of the application and wouldn't be the end of the world if it is not included in the initial release.

**Comment by cameronsmith223** [comment]
I think using pledge initiation number as a pass and school id as a
username would be good. Have is make a SQL query like count'*' from
table.entry where ID==(whatever they put) and pin==(what ever they put)
then if it returns andthing other then 1 it kicks them from the app. Just a
thought.

**Comment by lucaswalter** [comment]
I really like that idea. Just a simple one-time dialog then it saves it somehow so they don't need to be re-prompt each time.

**Comment by lucaswalter** [comment]
Not quite sure how saving would be done on the device... Maybe just local database?

**Comment by cameronsmith223** [comment]
Eh maybe a db on the server. The tables would never get larger than a few
gigabytes.

**Comment by lucaswalter** [comment]
I know we will need something on the server, but I think it would be a major pain for the user if they were re prompt each time they tried to use the app. Maybe it is possible on Android/iOS to create something like a Browser Cookie.

**Comment by cameronsmith223** [comment]
I think for Android there is something to the tune of an onFirstcreate but
I don't know for sure or how it works.

**Comment by lucaswalter** [comment]
I shall do some research.

**Comment by lucaswalter** [comment]
Here we go: https://stackoverflow.com/questions/7562786/android-first-run-popup-dialog

Basically we have a login dialog prompt on application start and check for the shared preference to see if the user was authenticated. Thoughts?

**Comment by cameronsmith223** [comment]
As long as a malicious user cannot dismiss the login dialog, close the app, re open the app and be past  the login.

**Comment by lucaswalter** [comment]
Right, the user will still be authenticated each time. It will just skip the dialog if the saved credential is valid, and will re-prompt if not.

**Comment by cameronsmith223** [comment]
Dank memes, right now I'm learning about SQL integration and database stuff in android apps. From what I can tell, iOS will be a completely different beast.
