### ISSUE TITLE
Redesign IM Data Model to support more IM functionality.

### ISSUE THREAD

**Issue by lucaswalter** [lucaswalter/Beta-Chi-Daily-Update#3]
This Data Model will need to be modified to support data such as signup dates, attendance, and league standings.

**Comment by cameronsmith223** [comment]
I think it should have spinners that provide Team(A,B,DG4L),Sport, Reminder Type(register deadline, game,tournament,championship), then fields for Time and Date. The IM chair fills out these fields and sets the reminders.

**Comment by lucaswalter** [comment]
I like that idea. Since this model and design will be much more advanced than pretty much all other pages/activities, I think we should get some mockup designs going to make sure we are completely on the same page for it.

**Comment by lucaswalter** [comment]
I also think we should keep functionality strictly to just reminders as we will be to just create a builder dialog with everything mentioned you mentioned above and will allow us to easily pass that data to the MainActivity reminderAdapter. 

For the initial release, I say we leave out leaderboards, as that would be something that would either require extensive manual input from the IM chair, or would require us to scrape that data off IM Leagues site. 

Once we get rolling after the first release/deployment we can get feedback from other on how they would like the leaderboards implemented.
