### ISSUE TITLE
Find some pretty colors for app theme

### ISSUE THREAD

**Issue by lucaswalter** [lucaswalter/Beta-Chi-Daily-Update#31]
I absolutely suck at anything design related. Feel free to change around any colors/styles/whatever else to make it look better.

**Comment by cameronsmith223** [comment]
I'M COLORBLIND YOU DROOLING NEANDERTHAL.

**Comment by lucaswalter** [comment]
Triggered

**Comment by cameronsmith223** [comment]
sRGB (255, 51, 0) and sRGB(80, 200, 120) could be good.
