### ISSUE TITLE
Add functionality for admin users to change password.

### ISSUE THREAD

**Issue by lucaswalter** [lucaswalter/Beta-Chi-Daily-Update#4]
Need to move authorization process to azure and allow users to change the passwords.

**Comment by lucaswalter** [comment]
Create new DB Table that maps a the text password to the Role and ID of the area they will be accessing.

**Comment by cameronsmith223** [comment]
Okie I just need the db. My SQL isn't too crummy

**Comment by lucaswalter** [comment]
My bad, forgot to get you access to it. The back end is much much much easier than you probably are thinking. We will just have to create a new class in the :"Core" folder that represents are entities and then make a base table through the portal. Azure will then auto generate a table for use.

**Comment by lucaswalter** [comment]
Decided on not including this in initial release, time looks like its gonna be a big issue.
