### ISSUE TITLE
Decide on removing save button on EditScribeDataActivity

### ISSUE THREAD

**Issue by lucaswalter** [lucaswalter/Beta-Chi-Daily-Update#43]
I've have been going back and forth on this a bit and could use another opinion on it. Currently, for any data entered by the scribe to be saved and sent to the database, the actual "Save Button" has to be pressed. 

I am thinking that it may be more user friendly to have the data automatically sent off whenever it is changed, but this brings up the issues of greatly higher data usage and the person entering in data can't easily undo an operatioin.

**Comment by cameronsmith223** [comment]
I would have it stay as an onclick. It gives the user a chance to
proofread.

**Comment by lucaswalter** [comment]
Cool, I will leave as is for now.
