### ISSUE TITLE
Decrease margin between the lower buttons in ScribeEditDataActivity.

### ISSUE THREAD

**Issue by lucaswalter** [lucaswalter/Beta-Chi-Daily-Update#5]

**Comment by cameronsmith223** [comment]
![image](https://cloud.githubusercontent.com/assets/12716681/8114244/2d036578-1041-11e5-85bd-e8ae76c1f819.png)

Do this. look at the margins for the buttons in the linear layout

**Comment by lucaswalter** [comment]
Margins have been fixed.
