### ISSUE TITLE
Determine what is causing the layouts to scale off screen on some emulators and devices.

### ISSUE THREAD

**Issue by lucaswalter** [lucaswalter/Beta-Chi-Daily-Update#8]

**Comment by cameronsmith223** [comment]
Not using pixel independent measurements.

**Comment by lucaswalter** [comment]
I believe that I have set up all layout to use density pixels correctly in the layouts. https://developer.android.com/guide/practices/screens_support.html

Looking at this, the only thing I believe we could switch would be the text to use "sp"

**Comment by lucaswalter** [comment]
Looking more into the emulator crashes. I believe it is currently a problem on Xamarin's side of things. I received the exact same error after downloading and trying to run their sample toolbar application. We may need to switch back too ActionBar.

**Comment by lucaswalter** [comment]
Maryland found that the sole reason for crashing was the toolbar as it only supports Android Lollipop, closing and making new issue.
